/* tslint:disable */
/* eslint-disable */
/**
 * PoenApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoinInfoDto } from './CoinInfoDto';
import {
    CoinInfoDtoFromJSON,
    CoinInfoDtoFromJSONTyped,
    CoinInfoDtoToJSON,
} from './CoinInfoDto';

/**
 * 
 * @export
 * @interface CoinInfoDtoPaginatedResult
 */
export interface CoinInfoDtoPaginatedResult {
    /**
     * 
     * @type {number}
     * @memberof CoinInfoDtoPaginatedResult
     */
    pageNo?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinInfoDtoPaginatedResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinInfoDtoPaginatedResult
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinInfoDtoPaginatedResult
     */
    totalRecords?: number;
    /**
     * 
     * @type {Array<CoinInfoDto>}
     * @memberof CoinInfoDtoPaginatedResult
     */
    data?: Array<CoinInfoDto> | null;
}

/**
 * Check if a given object implements the CoinInfoDtoPaginatedResult interface.
 */
export function instanceOfCoinInfoDtoPaginatedResult(value: object): value is CoinInfoDtoPaginatedResult {
    return true;
}

export function CoinInfoDtoPaginatedResultFromJSON(json: any): CoinInfoDtoPaginatedResult {
    return CoinInfoDtoPaginatedResultFromJSONTyped(json, false);
}

export function CoinInfoDtoPaginatedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoinInfoDtoPaginatedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNo': json['pageNo'] == null ? undefined : json['pageNo'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalRecords': json['totalRecords'] == null ? undefined : json['totalRecords'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CoinInfoDtoFromJSON)),
    };
}

export function CoinInfoDtoPaginatedResultToJSON(value?: CoinInfoDtoPaginatedResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pageNo': value['pageNo'],
        'pageSize': value['pageSize'],
        'totalPages': value['totalPages'],
        'totalRecords': value['totalRecords'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CoinInfoDtoToJSON)),
    };
}

