/* tslint:disable */
/* eslint-disable */
/**
 * PoenApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
} from './Token';

/**
 * 
 * @export
 * @interface TokenPaginatedResult
 */
export interface TokenPaginatedResult {
    /**
     * 
     * @type {number}
     * @memberof TokenPaginatedResult
     */
    pageNo?: number;
    /**
     * 
     * @type {number}
     * @memberof TokenPaginatedResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TokenPaginatedResult
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof TokenPaginatedResult
     */
    totalRecords?: number;
    /**
     * 
     * @type {Array<Token>}
     * @memberof TokenPaginatedResult
     */
    data?: Array<Token> | null;
}

/**
 * Check if a given object implements the TokenPaginatedResult interface.
 */
export function instanceOfTokenPaginatedResult(value: object): value is TokenPaginatedResult {
    return true;
}

export function TokenPaginatedResultFromJSON(json: any): TokenPaginatedResult {
    return TokenPaginatedResultFromJSONTyped(json, false);
}

export function TokenPaginatedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPaginatedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNo': json['pageNo'] == null ? undefined : json['pageNo'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalRecords': json['totalRecords'] == null ? undefined : json['totalRecords'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TokenFromJSON)),
    };
}

export function TokenPaginatedResultToJSON(value?: TokenPaginatedResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pageNo': value['pageNo'],
        'pageSize': value['pageSize'],
        'totalPages': value['totalPages'],
        'totalRecords': value['totalRecords'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TokenToJSON)),
    };
}

